AWSTemplateFormatVersion: '2010-09-09'
Description: Managed policies used by FHD. This is stacked in ALL team and classic
  accounts.
Resources:
  OpsAppIntegration:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: SNS policies for Operations Role.
      Path: /org-3/
      ManagedPolicyName: Test_Operations_Policy_Two
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sns:CheckIf*
              - sns:Get*
              - sns:List*
              - sns:Publish
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - sns:ConfirmSub*
              - sns:CreateTopic
              - sns:DeleteTopic
              - sns:SetTopic*
            NotResource:
              - !Sub arn:aws:sns:*:${AWS::AccountId}:ps-*
          - Effect: Allow
            Action:
              - sns:Subscribe
              - sns:Unsubscribe
            NotResource:
              - !Sub arn:aws:sns:*:${AWS::AccountId}:ps-test-*
              - !Sub arn:aws:sns:*:${AWS::AccountId}:ps-prod-*
          - Effect: Allow
            Action:
              - sns:DeleteTopic
            Resource:
              - '*'
            Condition:
              StringLike:
                aws:PrincipleTag/roleType:
                  - dpt
